### ISSUE TITLE
Custom end tag starting "{% end_" not indented.

### ISSUE THREAD

**Issue by Quantra** [rtts/djhtml#100]
When an end tag starts with `end_` it doesn't seem to be parsed correctly.

E.g. This works:

```
{% customtag %}
  <div>Works perfectly</div>
{% endcustomtag %}
```

But this does not:
```
{% custom_tag %}
<div>No indent</div>
{% end_custom_tag %}
```

And neither does this:
```
{% customtag %}
<div>No indent</div>
{% end_customtag %}
```

But my IDE (Pycharm) at least considers these all to be valid and I believe when creating a custom tag we can define it to be anything.  Starting it with `end` appears to be a best practice/convention and the use of underscores optional.

For reference the docs for creating advanced template tags uses examples with underscores in the name but the built in template tags (mostly) don't have underscores.  Somewhat ironically the docs use the `{% comment %}{% endcomment %}` as an example when parsing between tags, right after all the examples with underscores =]  https://docs.djangoproject.com/en/4.2/howto/custom-template-tags/#advanced-custom-template-tags

~~I have had a look into the code to see if I could spot a fix and make a PR but unforutnately I wasn't able to.~~  I have made a PR with a potential fix.  Thank you for your time and thank you for an otherwise invaluable tool in my work flow.

**Comment by JaapJoris** [comment]
Thank you very much for your contribution! Your PR has been approved, merged, and will be part of the next release.
