### ISSUE TITLE
djhtml style vs django docs style

### ISSUE THREAD

**Issue by minusf** [rtts/djhtml#104]
(i looked thru the old closed issues but didnt see this come up, i hope i didnt miss it)

afaik the django template language has no official styling guide, and in the past i have used both "dont ident django tags" vs "just indent everything". the beauty of black and djhtml is of course to stop these debates and just get on with it.

however the django docs overwhelmingly use a different style then what djhtml is enforcing:
```html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
```
vs
```html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
```
for me, who have learnt django by reading the documentation the current djhtml style is against django docs conventions and the reason why i don't use it in my personal solo projects (but use it in the team at work).

i was wondering if it would be possible to have that style behind a flag?

**Comment by jnns** [comment]
The Django docs are inconsistent when it comes to indentation and conditionals. The [documentation for the `{% if %}` template tag itself](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#if) uses the same indentation as djhtml:

```html
<!-- Django docs -->
{% if athlete_list %}
    Number of athletes: {{ athlete_list|length }}
{% elif athlete_in_locker_room_list %}
    Athletes should be out of the locker room soon!
{% else %}
    No athletes.
{% endif %}
```

```html
<!-- djhtml -->
{% if request.user.is_authenticated %}
    <h1>Welcome, {{ request.user }}</h1>
{% else %}
    <a href="{% url 'login' %}">Click here to login</a>
{% endif %}
```

In any case, I'd vote against adding a flag. An additional flag adds complexity to the project and increases the maintenance requirements.

**Comment by JaapJoris** [comment]
Agreed. The Django docs are inconsistent, and the Django source code even more so. This issue will be solved as soon as Django itself starts using DjHTML :grin:
