### ISSUE TITLE
Charmap error without tracability

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#113]
Hi @JaapJoris!

Without any changes, I now get this error:

> DjHTML...................................................................Failed
> - hook id: djhtml
> - exit code: 123
> 
> Error: 'charmap' codec can't decode byte 0x8f in position 19315: character maps to <undefined>
> 0 templates have been reindented.
> 227 templates were already perfect!
> 1 template could not be processed due to an error.

Is there any way I can see which template it doesn't like anymore? I have hundereds and git doesn't show me any changes. Didn't do an update, too.

Sorry that I can't provide more insight right now. 😔 

Thx!  
Ronny

**Comment by GitRon** [comment]
Ok, with divide-and-conquer I found the culprit!

I present: ⚠️

Hope this helps!

Supplemantal: Might be a Windows issue, UNIX colleage can lint this template.

**Comment by JaapJoris** [comment]
Yes, definitely a Windows issue. The [README](https://github.com/rtts/djhtml/blob/main/README.md) already contains this snippet to warn about this issue, added after the previous time it popped up:

> Note that [Windows still uses legacy code pages](https://docs.python.org/3/using/windows.html#win-utf8-mode) instead of UTF-8. It is highly advised to set the environment variable PYTHONUTF8 to 1 with the [setx](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setx) command:

    C:\> setx /m PYTHONUTF8 1

**Comment by GitRon** [comment]
Awesome! Thx @JaapJoris!
