### ISSUE TITLE
Unclosed attribute values cause superfluous indentation on subsequent runs

### ISSUE THREAD

**Issue by dleske** [rtts/djhtml#118]
Somewhat minor issue came up when using djhtml for our CI: I reformatted all our project templates, checked only whitespace had changed with `git diff -w`, and pushed the changes.  Then the CI failed because one file failed the indentation check (`djhtml -c`).  I found I could re-run `djhtml` on the problem file seemingly infinite times and it would keep re-indenting.

It turns out the problem is in an unclosed attribute value, and the file will be re-indented for as many passes as there are subsequent lines with attributes (or possible for each attribute, I didn't test with multiple in a given tag).

To reproduce, use the following `test.html`:

```
<html>
  <head><title>Hello, world</title>
  </head>
  <body>
    <h1>Hello, world</h1>

    <p class="this that label="Hi there">Hi there</p>

    <p id="hi">So then I sez to Mabel, I sez...</p>

    <p id="another-thing">So then I had another thing</P>

    <p id="harry">This just kept going on</p>
  </body>
</html>
```

It's valid-ish in the forgiving way of html.  Note the improper class specification in the first paragraph.  Here's how it looks like with `djhtml`:

```
$ djhtml -t2 test.html
reindented test.html
1 template has been reindented.
$ djhtml -t2 test.html
reindented test.html
1 template has been reindented.
$ djhtml -t2 test.html
reindented test.html
1 template has been reindented.
$ djhtml -t2 test.html
reindented test.html
1 template has been reindented.
$ djhtml -t2 test.html
0 templates have been reindented.
1 template was already perfect!
$ cat test.html
<html>
  <head><title>Hello, world</title>
  </head>
  <body>
    <h1>Hello, world</h1>

    <p class="this that label="Hi there">Hi there</p>

                                        <p id="hi">So then I sez to Mabel, I sez...</p>

                                                         <p id="another-thing">So then I had another thing</P>

                                                                                     <p id="harry">This just kept going on</p>
                                                                                                         </body>
                                                                                                         </html>
```

I'm not sure if this is worth fixing: the HTML wasn't valid in the first place, and if run through `xmllint --html` the unclosed attribute tag is flagged.  (But we can't run xmllint on everything prior to djhtml so might need something else there.)

**Comment by JaapJoris** [comment]
We've had a couple of similar issues in the past, which are all covered by this line in the README:

> The goal is to correctly indent already well-structured templates, not to fix broken ones.

When you feed DjHTML source code that is neither HTML, JS or CSS the results are unpredictable. That is both a bug and a feature; when something like this happens you will at least notice that something is wrong.

Thanks anyway for reporting this bug, which will now be closed :hugs:

**Comment by balazs-endresz** [comment]
I've just run into this last week too. It made it very easy to spot that something was wrong in the template, so it was actually helpful.

**Comment by dleske** [comment]
> We've had a couple of similar issues in the past, which are all covered by this line in the README:
> 
> > The goal is to correctly indent already well-structured templates, not to fix broken ones.
> 
> When you feed DjHTML source code that is neither HTML, JS or CSS the results are unpredictable. That is both a bug and a feature; when something like this happens you will at least notice that something is wrong.
> 
> Thanks anyway for reporting this bug, which will now be closed 🤗

Makes sense and totes fair.  Thanks for the reply! :)
