### ISSUE TITLE
Comments are not indented!

### ISSUE THREAD

**Issue by papansarkar101** [rtts/djhtml#120]
I have a big html file and this worked pretty well for formatting the whole code. However, the comments were not indented!

<img width="664" alt="image" src="https://github.com/user-attachments/assets/6e8df747-3f65-427b-9e02-8011cfd2da6f">

**Comment by balazs-endresz** [comment]
I think comments are skipped on purpose, see readme, and more context here: https://github.com/rtts/djhtml/releases/tag/3.0.0#:~:text=comment%20tags%20are%20now%20ignored

But I wonder if an exception could be made for single line comments, so that only those were indented?

**Comment by papansarkar101** [comment]
Thank you for pointing me to the relevant documentation. I understand that comment tags are ignored by design. 

Yeah right, I wonder if an exception could be made for single-line comments to be indented. This would help maintain readability and consistency in code formatting, especially in large HTML files.

Is this something that could be considered for a future update?

**Comment by JaapJoris** [comment]
As explained in [the release notes linked above](https://github.com/rtts/djhtml/releases/tag/3.0.0) (thanks!), indenting comments correctly is hard:

```html
<div>
    <p>
        {# ╔══════════════════════════╗
   ║ Carefully laid out table ║
   ╚══════════════════════════╝ #}
    </p>
</div>
```

The same applies for JavaScript and CSS comments. You could argue that the above is a multi-line comment, and that only single line comments should be indented. However, DjHTML doesn't "know" whether a comment is multi-line or not, at least not without parsing the entire comment for newlines. Moreover, it will still lead to inconsistencies when single- and multi-line comments appear together, for example:

```javascript
function foo(bar) {
    /* Return bar */
    /* Arguments:
     * - bar
     */
    return bar;
}
```

So the easiest solution remains to just ignore comments altogether.

**Comment by papansarkar101** [comment]
Thank you for your response @JaapJoris @balazs-endresz
