### ISSUE TITLE
djhtml creates new output file, even when it shouldn't

### ISSUE THREAD

**Issue by sjoerdjob** [rtts/djhtml#15]
When `djhtml -o file arg1` is called, the file is opened for writing before the existence of `arg1` is verified.

When `djhtml -o file arg1 arg2` is called, the file is opened for writing before an exception is raised about not modifying files in-place.

In both cases, either a new file is created with empty contents, *or* an existing file is truncated.

**Comment by JaapJoris** [comment]
This bug is an unfortunate side-effect of calling `argparse.FileType("w")` in `__main__.py`. Argparse truncates the file before it's being used. In combination with #14 this can can destroy existing files so I have added the label severe.

**Comment by JaapJoris** [comment]
Closed by ec64cfa042126e4c
