### ISSUE TITLE
Incorrect parse when greater-than comparison in DTL-if inside HTML tag

### ISSUE THREAD

**Issue by sjoerdjob** [rtts/djhtml#20]
```
<!-- if with greater than inside tag -->
<div {% if foo > bar %} class="baz"{% endif %}>
    quux
</div>
```

The tokenizer seems to interpret `<div {% foo >` as the tag.

```
found closing “{% endif %}” on line 2 while expecting “</div>”
```

**Comment by JaapJoris** [comment]
In order to solve this, the tokenizer should make 2 passes over the source instead of just 1. In the first pass, only django template tags should be recognized, while in the second pass the mode-specific tags should be tokenized. This will require some refactoring. I'm on it!
