### ISSUE TITLE
Could you also support jinja templates?

### ISSUE THREAD

**Issue by pgjones** [rtts/djhtml#22]
Thanks for building this, its been on my wish list for a while. 

I think it wouldn't be too hard to support Jinja2 templates as well (I think the syntax is very similar), would this be something you are willing to do?

**Comment by JaapJoris** [comment]
Thank you for the excellent suggestion! I've had a quick browse through https://jinja.palletsprojects.com/templates/ and if I'm not mistaken, DjHTML currently already supports all of the main constructs in Jinja templates. In particular, the doc's opening example is rendered correctly by DjHTML:

```jinja
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>My Webpage</title>
    </head>
    <body>
        <ul id="navigation">
            {% for item in navigation %}
                <li><a href="{{ item.href }}">{{ item.caption }}</a></li>
            {% endfor %}
        </ul>

        <h1>My Webpage</h1>
        {{ a_variable }}

        {# a comment #}
    </body>
</html>
```

What Jinja syntax would still need to be implemented in DjHTML for full Jinja2 support?

**Comment by notpushkin** [comment]
There might be some good examples here? https://github.com/justrhysism/prettier-plugin-nunjucks/tree/master/tests I'm not sure if those would be in scope of this project but still might be worth looking into :-) You can also state the support for Jinja2 (and maybe Twig/Nunjucks?) in README, if you do want to support it.

And of course, thank you so much for this project! This is something long awaited by the Jinja2 user community in particular.

**Comment by JaapJoris** [comment]
I have updated the documentation to explicitly announce Jinja2 support!

I will close this issue now, but if you (or any other Jinja user) has any issues regarding the processing of Jinja2 templates, let it be known that you are more than welcome to open new issues! :hugs:

**Comment by pgjones** [comment]
This is great, thank you.

**Comment by davidism** [comment]
Really nice to see this, thank you!

Some other things to consider in the future:

- Jinja has comment syntax, can't remember if Django does.
- Jinja's delimiters can be customized.
- Jinja has a "line statement" syntax that can be enabled by specifying delimiters for it.

**Comment by notpushkin** [comment]
@davidism [It seems](https://stackoverflow.com/a/52465629/1593459) that Django has a syntax similar to Jinja's (`{# ... #}`) that only works as a single line for some reason (they also have `{% comment %}` block for multiline comments). I'm not sure though if there's any sensible way to support comments except treating them as raw strings?
