### ISSUE TITLE
Comment body doesn't get re-indented properly when indenting comment-start

### ISSUE THREAD

**Issue by sjoerdjob** [rtts/djhtml#23]
What I notice is that with the latest indenting algorithm, comments don't get properly re-indented.

While the current algorithm is at least stable (i.e.: comment-body doesn't move if comment-opening doesn't move), I think it would be better if the code is updated to ensure that when a comment-opening moves, the body moves along with it.

Reason for this is that in longer files, people might not have fixed the indents of the whole file, but will likely at least have ensured that the indenting is "locally proper" in the section they're working on.

Input:
```
<div>
    <div>
    <!--
    here is some comment
    -->
    </div>
</div>
```

Actual output:
```
<div>
    <div>
        <!--
    here is some comment
    -->
    </div>
</div>
```

Expected output:
```
<div>
    <div>
        <!--
        here is some comment
        -->
    </div>
</div>
```

**Comment by JaapJoris** [comment]
I agree that the closing `-->` should be indented to the same level as the opening `<!--`, but only if it is preceded by just whitespace. However, I don't think that DjHTML should process the lines in between, because comments should be allowed to be free-form.

**Comment by JaapJoris** [comment]
After giving it some more consideration, I believe that the following, while it looks ugly, is the correct way to indent "ignored" sections like comments and `<pre>` tags.

```html
<div>
    <pre>
Preformatted
</pre>
</div>
```

Everything between the start and end tag should be ignored, and that necessarily means that no whitespace should be inserted even on the final line. It's tough, but for now this unfortunately means manually reindenting your comments when the surrounding indentation level changes.
