### ISSUE TITLE
Skip certain lines/Retain Indentation

### ISSUE THREAD

**Issue by rickdonato** [rtts/djhtml#29]
Is there a way to skip the formatting of certain lines. or retain there current indentation. For example:

```
❯ cat   example2.j2
{% if router_bgp %}
{%    for neighbor in bgp_neighbors %}
router bgp {{ router_asn }}
   neighbor {{ neighbor['ip'] }} description {{ neighbor['description'] }}
   neighbor {{ neighbor['ip'] }} peer-group {{ neighbor['peer_group'] }}
{%    endfor %}
{% endif %}
```
```
❯ djhtml  example2.j2
{% if router_bgp %}
    {%    for neighbor in bgp_neighbors %}
        router bgp {{ router_asn }}
        neighbor {{ neighbor['ip'] }} description {{ neighbor['description'] }}
        neighbor {{ neighbor['ip'] }} peer-group {{ neighbor['peer_group'] }}
    {%    endfor %}
{% endif %}
```

Is there a way to prevent any indentation for the router and neighbour lines for example or keep their current indentation, and append?

**Comment by JaapJoris** [comment]
Hi there, and thanks for contributing! This feature was added in 11186526676fffe520d96c9e498f3d3f168c3234 but I forgot to document it. My apologies. You can exclude specific lines from being processed with the `{# fmt:off #}` and `{# fmt:on #}` operators:

```jinja
<div class="
    {# fmt:off #}
      ,-._|\
     /     .\
     \_,--._/
    {# fmt:on #}
/>
```

I have added this cute little bunny to the README as well!
