### ISSUE TITLE
Feature request: Command-line options

### ISSUE THREAD

**Issue by JaapJoris** [rtts/djhtml#3]
It would be nice to have some more control over DJHTML's behavior through command-line arguments. @sjoerdjob suggested the following options:

- `--check` to only check files and not alter their contents
- `--diff` to show the diff between the input file and the would-be output file
- support for multiple files as arguments
- support for directory names as arguments

**Comment by sjoerdjob** [comment]
While working on this, it would probably also be good to not overwrite the file when nothing has changed.

Would you prefer to use a dependency like [Click](https://click.palletsprojects.com/en/8.0.x/) for command-line parsing, or is optargs/argparse good enough, with the benefit of no dependencies?

**Comment by JaapJoris** [comment]
`argparse` will do fine. Let's try to keep DJHTML as dependency-free as possible. Although I have to admit I'm mouthwatering at [pytidylib](https://pypi.org/project/pytidylib/)...
