### ISSUE TITLE
Still pretty verbose when running `pre-commit run --all-files`

### ISSUE THREAD

**Issue by richarddewit** [rtts/djhtml#31]
When running `pre-commit run --all-files` it's still pretty verbose:

```
djhtml...................................................................Failed
- hook id: djhtml
- files were modified by this hook

All done! \o/
16 templates left unchanged.
All done! \o/
16 templates left unchanged.
All done! \o/
16 templates left unchanged.
All done! \o/
16 templates left unchanged.
All done! \o/
16 templates left unchanged.
All done! \o/
16 templates left unchanged.
reindented babeldat/core/templates/partials/_menu.html
All done! \o/
1 template reindented, 15 templates left unchanged.
All done! \o/
11 templates left unchanged.
```

FYI: I had 16 files staged, only 4 of them were templates

**Comment by JaapJoris** [comment]
That is indeed pretty verbose :joy: 

Do you still experience this issue with the latest version? The current branch `main` prints the following output:

```
djhtml...................................................................Failed
- hook id: djhtml
- files were modified by this hook

reindented template1.html
reindented template2.html
reindented template3.html
... [etc]
67 templates have been reindented.
44 templates were already perfect!
```

**Comment by JaapJoris** [comment]
I've [released a new version](https://github.com/rtts/djhtml/releases/) that contains the improved output formatting. You can now upgrade with `pre-commit autoupdate`. Thank you for your help!

**Comment by JaapJoris** [comment]
I tested it again with version 1.4.3 but the output is still too verbose:

```
$ pre-commit run --all
djhtml...................................................................Failed
- hook id: djhtml
- files were modified by this hook

reindented jaapjoris/templates/base.html
reindented jaapjoris/templates/cms/page.html
reindented jaapjoris/templates/text.html
reindented jaapjoris/templates/button.html
4 templates have been reindented.
reindented jaapjoris/templates/video.html
reindented jaapjoris/templates/contact.html
reindented jaapjoris/templates/image.html
3 templates have been reindented.
```

It seems that pre-commit has called `djhtml` two times: Once with 4 arguments and once with 3. How can you tell pre-commit not to do that? :thinking:

**Comment by richarddewit** [comment]
> How can you tell pre-commit not to do that?

¯\\\_(ツ)\_/¯

**Comment by JaapJoris** [comment]
Found it: setting `require_serial` to `true` will cause pre-commit to only call `djhtml` once. This produces much nicer output so I've updated the default pre-commit hook. In theory, parallel processing would make it faster but in practice I didn't notice much difference anyway ¯\\\_(ツ)\_/¯
