### ISSUE TITLE
Jinja "whitespace control" is not understood

### ISSUE THREAD

**Issue by sjoerdjob** [rtts/djhtml#36]
Jinja allows one to control whitespace generated by tags. For instance:

```
<div>
    {% for item in sequence %}
        {{ item }}
    {%- endfor %}
</div>
```

but DjHTML then misses the `endfor`.

**Comment by JaapJoris** [comment]
Thank you very much for reporting this issue! I have updated the regex for raw token detection to:

    {%[-\+]?.*?[-\+]?%}

You can find it in [the latest release](https://github.com/rtts/djhtml/releases).

**Comment by markus-beuckelmann** [comment]
Reopening this issue here. I tried the above example and various combinations of `{%-`, `{%`, `-%}`, `%}` with the new `1.4.7` release but it still does not format correctly. Furthermore, most likely related, consider the following example from one of my templates:

```
{%- macro render_currency(currency, amount) -%}

{% if currency == "USD" %}
  {{ amount }}
{% else %}
  {{ amount|convert("USD") }}
{% endif %}

{%- endmacro -%}
```

But:

```
{%- macro render_currency(currency, amount) -%}

    {% if currency == "USD" %}
        {{ amount }}
    {% else %}
        {{ amount|convert("USD") }}
    {% endif %}

{% endmacro %}
```

**Comment by sjoerdjob** [comment]
@JaapJoris : the regex for detecting the closing tag also needs to be extended with the `[-+]?`.

Maybe also the `{% endcomment` regex, but I think that's a Django-only tag anyway.

**Comment by JaapJoris** [comment]
Thanks people! The issue has been fixed in [the latest release](https://github.com/rtts/djhtml/releases/)!
