### ISSUE TITLE
Incorrect indentation in places with multiple template tags

### ISSUE THREAD

**Issue by apoorvaeternity** [rtts/djhtml#38]
Hey,

I am using this library as a `pre-commit` hook already. It works really well in most places. I am just hitting an issue mostly around the code involving [django_components](https://github.com/EmilStenstrom/django-components) as it uses a lot of template tags.

Here's an example:
```
{% component_block "instruction" border_top=True header="Login" %}
    {% slot "body" %}
      {% with "login --token="|add:token as content %}
        {% component "copy_field" field_selector="token-field" content=content %}
        {% endwith %}
      {% endslot %}
    {% endcomponent_block %}
```
As you can see the `endwith` tag has unneeded indentation and same with the other `end...` tags.

**Comment by JaapJoris** [comment]
Hi there, and thanks for reporting this bug! We are currently working on improving the `{% end... %}` tag detection, and this issue will certainly be taken into consideration as well. Currently, DjHTML incorrectly assumes that the `{% component %}` tag is closed by the `{% endcomponent_block %}` tag and therefore considers it an opening tag, which of course isn't the case. I deduced this from the output of `djhtml -d` (the "tokenization debug mode"):

```
$ djhtml test.html -d
(Open:'{% component_block "instruction" border_top=True header="Login" %}')
(Open:'{% slot "body" %}')
(Open:'{% with "login --token="|add:token as content %}')
(Open:'{% component "copy_field" field_selector="token-field" content=content %}')
(Close:'{% endwith %}')
(Close:'{% endslot %}')
(Close:'{% endcomponent_block %}')
```

I will keep you updated as soon as this is fixed!

**Comment by JaapJoris** [comment]
Hi there, just wanted to let you know this bug's been fixed in [the latest release of DjHTML](https://github.com/rtts/djhtml/releases). Thanks again for reporting it, and feel welcome to report more issues when you find them!

**Comment by apoorvaeternity** [comment]
@JaapJoris - Thanks for the immediate response.
