### ISSUE TITLE
Get file through stdin

### ISSUE THREAD

**Issue by tissieres** [rtts/djhtml#42]
Hello,

Thanks for this great tool. I'm using it for formatting my templates with efm. It would be great if we could open the template through stdin since it would let us use it without needing to save the file beforehand. Currently, if I forgot to save the file before running djhtml, my edits are lost. 

Thanks

**Comment by JaapJoris** [comment]
First of all, I'm really curious what you mean by [efm](https://en.wikipedia.org/wiki/EFM) :-)

But to answer your question: it is already possible to pipe a template to DjHTML's `stdin`. You can either use `djhtml` with no arguments:

```
$ cat template.html | djhtml
<h1>Hello, world!</h1>
```

Or you can use the "special" argument `-`:

```
$ cat template.html | djhtml -
<h1>Hello, world!</h1>
```

In both cases, the output will be written to `stdout`. If you try the `-i` / `--in-place` switch while supplying the template on `stdin`, you will discover the following easter egg:

```
$ cat template.html | djhtml -i
I’m sorry Dave, I’m afraid I can’t do that
```

**Comment by tissieres** [comment]
Thanks for your answer and sorry for missing that. I did not find any mention of this in the help or README. 

I was talking about [efm-langserver](https://github.com/mattn/efm-langserver) by the way.

**Comment by JaapJoris** [comment]
Well, it wouldn't be much of an easter egg if it was mentioned in the README ;-)

But you are right, standard input wasn't mentioned at all. I've updated the README to explain this behavior, minus the easter egg.
