### ISSUE TITLE
Indentation of multiline JS comments in script tags

### ISSUE THREAD

**Issue by thibaudcolas** [rtts/djhtml#60]
The following HTML:

```html
<script>
/*
  Get the thing
 */
const getTheThing = () => theThing;
</script>
```

gets indented as: 

```html
<script>
    /*
  Get the thing
 */
    const getTheThing = () => theThing;
</script>
```

It looks like djhtml might not have support for multi-line comments in JS? I was able to manually indent the comments and there were no further issues, but thought I’d check whether this is known or not.

**Comment by JaapJoris** [comment]
Duplicate of #58
