### ISSUE TITLE
Throws error on windows with unicode

### ISSUE THREAD

**Issue by spapas** [rtts/djhtml#68]
Hello, I'm trying to use this tool on a windows system to ident an html file containing unicode characters. The file is in utf-8.

When I try to run I get the following error:

```
> djhtml -i templates\home.html
Error opening templates\home.html: 'charmap' codec can't decode byte 0x81 in position 457: character maps to <undefined>
0 templates have been reindented.
1 template could not be processed due to an error.
```

Notice that this happens only when the template contains greek characters, when I try it on a file with non-unicode characters it works fine. 

I noticed that this error can be resolved if we change the line 97 of `__main__.py` from

```
                sys.stdin if input_filename == "-" else open(input_filename, "r")
```
to
```
                sys.stdin if input_filename == "-" else open(input_filename, "r", encoding="utf-8")
```

and the line 147 from
```
                output_file = open(output_filename, "w")
```
to
```
                output_file = open(output_filename, "w", encoding="utf-8")
```

I understand that we can't enforce this encoding to all files, however what I propose is to add an optional `-e` / `--encoding` parameter to djhtml. If this parameter isn't used then the behavior of the program will be the same. If however this parameter has a value this value will be passed to the `open` function when reading and writing as `encoding="value"`).

If you agree with this proposal I'd be happy to provide a PR.

Kind regards,
Serafeim

**Comment by JaapJoris** [comment]
Hi there, and thanks for reporting this bug!

I see no objections to hard-coding `encoding="utf-8"` into DjHTML, and frankly I am a little surprised that isn't Python's default value for `open()` anyway. I don't think there are many (or any) people using DjHTML for non-UTF files.

However, another solution would be so set the environment variable `PYTHONUTF8` to `1`, see https://docs.python.org/3/library/os.html#utf8-mode

On Windows, you can do so with the following command

```
setx /m PYTHONUTF8 1
```

**Comment by spapas** [comment]
@JaapJoris thank you for this tip! After I used `set PYTHONUTF8=1` it worked flawlessly! 

I wasn't familiar with this parameter but from now I'm gonna make heavy use of it :)

Kind regards,
Serafeim
