### ISSUE TITLE
Wrong indention of multi-line @font-face declaration

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#74]
Hi @JaapJoris 

I am truely sorry for raising that many issues 😅 I just saw this odd behaviour... I guess this is not intended, is it? (the right side is after the reformatting)

![grafik](https://user-images.githubusercontent.com/3176075/217170360-2fbe4a16-9c9a-4e3f-ae0d-3133e9862ff3.png)

Thx!
Ronny

**Comment by JaapJoris** [comment]
Please don't apologize, and thank you for discovering another bug! This is definitely not the correct behavior, and I will see what I can do to fix it.

**Comment by JaapJoris** [comment]
Thanks again for your contribution! [DjHTML 3.0.0](https://github.com/rtts/djhtml/releases/tag/3.0.0) has just been released and fully supports multi-line variable assignments, including many edge cases covered by unittests.

**Comment by GitRon** [comment]
Awesome! Thx alot! ❤️
