### ISSUE TITLE
Incorrect indentation of `{{ '<tag>' if condition }}`

### ISSUE THREAD

**Issue by globau** [rtts/djhtml#75]
Input

```
{{ '<b>' if condition }}
some text
{{ '</b>' if condition }}
more text
```

Actual

```
{{ '<b>' if condition }}
    some text
    {{ '</b>' if condition }}
more text
```

Expected (matches formatting when the conditional string doesn't contain an element)

```
{{ '<b>' if condition }}
some text
{{ '</b>' if condition }}
more text
```

_or_ (matches formatting when the elements are not conditional)

```
{{ '<b>' if condition }}
    some text
{{ '</b>' if condition }}
more text
```

**Comment by JaapJoris** [comment]
Thanks for reporting this bug!

Currently, DjHTML has no notion of `{{` and `}}` and just treats them as text. When it sees the `<b>` tag it thinks it needs to indent. The solution, therefore, is to introduce a new mode `InsideTemplateVariable` that ignores everything until the closing `}}`. I don't think it would be that complicated after reading the source and understanding how the other modes work.

Is anyone willing to pick this up and create a PR?

**Comment by JaapJoris** [comment]
Thanks again for contributing this bug. [DjHTML 3.0.0](https://github.com/rtts/djhtml/releases/tag/3.0.0) has just been released so it has now officially been fixed. Feel free to report more bugs in the future!
