### ISSUE TITLE
Bug with django-cms placeholder templatetag

### ISSUE THREAD

**Issue by corentinbettiol** [rtts/djhtml#78]
We found a strange behavior today:

Here's a sample of html code that are using the django-cms [`placeholder`](https://docs.django-cms.org/en/latest/reference/templatetags.html#placeholder) templatetag: 

```django
{% block main %}
  <section>
    <div>
      <div>
        {% placeholder "placeholder1" %}
      </div>
      <div>
        {% placeholder "placeholder2" or %}
          <img src="" alt="" />
        {% endplaceholder %}
      </div>
    </div>
  </section>
  <section>
    <div>
      {% placeholder "placeholder3" %}
    </div>
  </section>
  <section>
    <div>
      {% placeholder "placeholder4" %}
    </div>
  </section>
{% endblock main %}
```

Notice the `{% placeholder "placeholder2" or %}` instruction? It tells to display the content of "placeholder2" OR an img if the placeholder is empty.

This line is breaking djhtml reaaally bad.

Here's the formatted code that djhtml outputs:

```django
{% block main %}
  <section>
    <div>
      <div>
        {% placeholder "placeholder1" %}
          </div>
          <div>
            {% placeholder "placeholder2" or %}
              <img src="" alt="" />
            {% endplaceholder %}
          </div>
          </div>
          </section>
          <section>
            <div>
              {% placeholder "placeholder3" %}
            </div>
          </section>
          <section>
            <div>
              {% placeholder "placeholder4" %}
            </div>
          </section>
      {% endblock main %}
```

Can you specify that djhtml does *not* work with django-cms-related tags somewhere in the README? (*or better make it compatible with the strange templatetags of django-cms, but it may take a lot more time*)

**Comment by JaapJoris** [comment]
Thanks for reporting this bug!

This issue will be fixed in the next release of DjHTML, which is due shortly :partying_face:

**Comment by corentinbettiol** [comment]
Wow, that *really* was fast! Thanks!

**Comment by JaapJoris** [comment]
Hi there, I'd just like to inform you that [DjHTML 3.0.0](https://github.com/rtts/djhtml/releases/tag/3.0.0) has just been released, including a fix for this bug. Thanks again for reporting it and I'm looking forward to more bugs in the future!

**Comment by corentinbettiol** [comment]
Thank you very much for all this work, it's making our work so much easier!
