### ISSUE TITLE
Indention for many attribute values and trailing attribute a little odd

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#80]
Hi @JaapJoris 

thx for the update! Here is one tiny thing that's a little odd.

When I have an attribute with many values (like my class here), the values get aligned and the trailing attribute `tag-object` stays in the same line. I would expect that it moves to the next line because it's too far on the right.

Here's a screenie of the effect:

![grafik](https://user-images.githubusercontent.com/3176075/220840222-193a5052-4361-4c44-b570-c6e07ae37f0d.png)

To make it reproducible for you:

````html
<div class="table-container">
                            <table id="datatable_client" class="dataTables_client table table-striped table-bordered
                                                                table-hover table-checkable dataTable no-footer" table-object="client">
                                <thead class="green-btn">
                                    <tr role="row" class="heading">
                                        <th>{% trans "Bezeichnung" %}</th>
                                        <th width="20%">{% trans "SGE" %}</th>
                                        <th width="20%">{% trans "Aktiv" %}</th>
                                        <th width="10%" class="no-sort">{% trans "Aktionen" %}</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
````

Best from Cologne
Ronny

**Comment by JaapJoris** [comment]
Bonjour! 

DjHTML only adds or removes whitespace. It will not insert newlines. I understand why that would look better, but you'd have to insert them yourself.

**Comment by GitRon** [comment]
Fine for me, thx for the clarification. Maybe something for the docs, if it's not yet in there?

**Comment by JaapJoris** [comment]
Actually, in the second paragraph :innocent: 

> DjHTML is an _indenter_ and not a _formatter_: it will only add/remove
> whitespace at the beginning of lines. It will not insert newlines or
> other characters. The goal is to correctly indent already
> well-structured templates, not to fix broken ones.

**Comment by GitRon** [comment]
Ok, my bad! 😆
