### ISSUE TITLE
Support for Slippers' reusable component syntax

### ISSUE THREAD

**Issue by jnns** [rtts/djhtml#86]
There's this great library called [slippers](https://mitchel.me/slippers/) that makes writing reusable components for the Django Template Language a joy. 

In your opinion, would it make sense to support them? I for one would welcome it!

In this example from the slippers website indentation DjHtml currently removes the indentation:

```django
{% #quote %}
  {% quote_photo src="/project-hail-mary.jpg" %}

  {% #quote_text %}
    “I penetrated the outer cell membrane with a nanosyringe."
    "You poked it with a stick?"
    "No!" I said.
    "Well. Yes. But it was a scientific poke with a very scientific stick.”
  {% /quote_text %}

  {% #quote_attribution %}Andy Weir, Project Hail Mary{% /quote_attribution %}
{% /quote %}
```

```django
{% #quote %}
{% quote_photo src="/project-hail-mary.jpg" %}

{% #quote_text %}
“I penetrated the outer cell membrane with a nanosyringe."
"You poked it with a stick?"
"No!" I said.
"Well. Yes. But it was a scientific poke with a very scientific stick.”
{% /quote_text %}

{% #quote_attribution %}Andy Weir, Project Hail Mary{% /quote_attribution %}
{% /quote %}
```

**Comment by JaapJoris** [comment]
I checked out Slippers and it seems like an awesome project!

Adding support to DjHTML to recognize `{% #name %}` as an opening token and `{# /name %}` as a closing token wouldn't be too hard, although I'm wondering why Slippers didn't choose to use the more conventional Django syntax of `{% component name %}` / `{% endcomponent name %}` which is already supported by DjHTML, and by many code editors.

**Comment by jnns** [comment]
I assume using explicit opening/closing characters is necessary because child elements are optional. In a situation like this the template tag parser wouldn't know which is an opening tag with children and which is a standalone tag:

```django
{% icon_button icon="envelope" %}
{% icon_button icon="envelope" %}Submit{% endicon_button %}
```

**Comment by jansonsiy-yeoki** [comment]
Hi @jnns! I am encountering an issue.

for example:

in this block of code:

```
{% #header_component %}
    {% header_title_component title="my title" %}
{% /header_component %}
```

is being corrected automatically by djhtml to:

```
{% #header_component %}
{% header_title_component title="my title" %}
{% /header_component %}
```

I saw that you have already fixed this I think? Basing on the tests
[test in](https://github.com/jnns/djhtml/commit/512cdb0d00e7e65a2f8362b4d93ad38338f3ba0a#diff-a55858503352ebd3661ed212110d3032a677ed412ba81c721f9f1d5573e49f59R114)
[test out](https://github.com/jnns/djhtml/commit/512cdb0d00e7e65a2f8362b4d93ad38338f3ba0a#diff-76ba81b46e7fdfd35a392139690ecf5fb2f1d707c61902f6490afe5ad3fb3233R114)

it should not be indenting wrongly in this case

- djhtml version: 3.0.2
- Django version: 4.1.10
- slippers version: 0.5.0

**Comment by jnns** [comment]
Works for me. If the djhtml version 3.0.2 you specified is in deed the one you're using, that behavior is expected. Slippers support has been introduced in 3.0.3. 

Please upgrade to the newest version of djhtml 3.0.6 and provide an example where djhtml does not work as expected. 

If you're on 3.0.6 and still running into issues with Slippers components, please also check out the newest pull request https://github.com/rtts/djhtml/pull/102 that's not yet merged into the main branch but fixes another bug with Slippers components.
