### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pierre-chataigner** [rtts/djhtml#95]
Hi,

I've encountered this error.
![djhtml](https://user-images.githubusercontent.com/68419774/227527308-4567a06d-e5eb-415e-9489-7eee7591a293.PNG)
with python 3.9.5
I believe it might be solved by replacing 
`if changed := _verify_changed(source, result):`
by
`if (changed := _verify_changed(source, result)):` (with parenthesis)
in accordance with [PEP 572 : Relative precedence of :=](https://peps.python.org/pep-0572/#relative-precedence-of)

**Comment by JaapJoris** [comment]
The walrus operator currently appears in the following places:

```
djhtml/__main__.py
88:        if changed := _verify_changed(source, result):

djhtml/lines.py
51:        if text := self.text.strip():
68:            if value := getattr(self, attr):

djhtml/modes.py
217:        if tag := re.match(self.OPENING_TAG, raw_token):
246:        if regex := self.AMBIGUOUS_BLOCK_TAGS.get(name):
290:            if match := re.match(r"([\w\-\.:]+)(\s*)", src):
317:            if tagname := re.search(r"\w+", raw_token):

djhtml/tokens.py
34:                if value := getattr(self, attr):
```

Are you saying that all of these usages are incorrect? Then why do the [unittests pass](https://github.com/rtts/djhtml/actions/runs/4441940982) with Python 3.8, 3.9, 3.10 and 3.11?

**Comment by pierre-chataigner** [comment]
Problem came from my side, my bad.
