### ISSUE TITLE
Add support for reading tab width from a config file

### ISSUE THREAD

**Issue by kbayliss** [rtts/djhtml#96]
While we can use `--tabwidth x` to control the tab width when invoking `djhtml`, this requires you to consistently invoke it, which is not guaranteed - especially if you are testing locally by running `djhtml` directly, then with `pre-commit`, and then within CI.

If `djhtml` could read tab width from a centralised config (e.g. pyproject.toml, setup.cfg, etc), then this would make using the tool more reliable.

**Comment by paduszyk** [comment]
Alternatively, one could take the tab width from `.editorconfig`. But config files like (preferably, the `pyproject.toml`) should be parsed as first.

**Comment by JaapJoris** [comment]
Thank you for your suggestion to improve DjHTML! In the past, we've had [various proposals](https://github.com/rtts/djhtml/issues/40#issuecomment-876334985) for a configuration file, but it was never implemented. There's currently only 1 thing configure anyway: the tabwidth.

Also, there _is_ a configuration file already: `.pre-commit-config.yaml`. You can use it specify a default tabwidth like so:

```yaml
repos:
  - repo: https://github.com/rtts/djhtml
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2
```

Also, once your templates are somewhat correctly indented, you can run `djhtml .` without further arguments to re-indent them, and it will use the existing indentation to "guess" the correct tabwidth, which will work correctly in 99% of cases. When it doesn't, running `pre-commit run djhtml -a` is another way to run DjHTML, forcing the tabwidth configured above.

Given these possibilities, I don't think it's absolutely necessary to introduce a configuration file to specify the tabwidth. If someone wants to create a PR to do so anyway, I'll be happy to merge it as long as it doesn't introduce any new dependencies. Until then, please forgive me for closing this issue.

**Comment by kylebayler** [comment]
@JaapJoris .pre-commit-config.yaml is only for pre-commit, which means running djhtml directly requires developers to remember to include the `--tabwidth` argument, and again within CI, developers must ensure they pass the `--tabwidth` argument as part of their pipeline config.

I appreciate this means it is possible (as identified in the original issue) to use djhtml with the same tab width configured, but it involves a lot of room for error, which I think could be improved.

The suggestion is to [follow djLint's approach and read from a config file](https://www.djlint.com/docs/configuration/).

**Comment by JaapJoris** [comment]
@kbayliss I agree, and as I said I'll happily accept a PR that introduces additional ways to configure the tabwidth :hugs:

**Comment by JaapJoris** [comment]
By the way, in my personal pipelines I don't run each tool individually, but `pre-commit run --all` which makes DjHTML adhere to the tabwidth configured in `.pre-commit-config.yaml`.
